# Data Preprocessing and Logistic Regression - Sklearn

In [1]:
# Package importing

import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import numpy as np
from AdvancedAnalytics import logreg
from sklearn.metrics import confusion_matrix

In [5]:
# Data File importing

sonar=pd.read_excel('C:/Users/NITESH/Desktop/isen-656/sonar3by5.xlsx')
sonar.head()

,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,...,R52,R53,R54,R55,R56,R57,R58,R59,R60,object
0,NaN,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,NaN,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,NaN,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,NaN,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
##Oultier detection

list=['R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11',
       'R12', 'R13', 'R14', 'R15', 'R16', 'R17', 'R18', 'R19', 'R20', 'R21',
       'R22', 'R23', 'R24', 'R25', 'R26', 'R27', 'R28', 'R29', 'R30', 'R31',
       'R32', 'R33', 'R34', 'R35', 'R36', 'R37', 'R38', 'R39', 'R40', 'R41',
       'R42', 'R43', 'R44', 'R45', 'R46', 'R47', 'R48', 'R49', 'R50', 'R51',
       'R52', 'R53', 'R54', 'R55', 'R56', 'R57', 'R58', 'R59', 'R60']

def outlier(x):
    if x<0 or x>1:
        x=None
    else:
        x=x
    return x

for i in list:
    sonar[i]=sonar[i].apply(lambda x : outlier(x))

In [6]:
##Imputing the missing value with the mean   

interval_data=sonar.as_matrix(columns=list)
interval_impute=preprocessing.Imputer(strategy='mean')
imputed_interval_data=interval_impute.fit_transform(interval_data)
sonar[list]=imputed_interval_data
sonar.head()

C:\Users\NITESH\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until

,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,...,R52,R53,R54,R55,R56,R57,R58,R59,R60,object
0,0.029013,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.310900,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.045300,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.333700,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.029013,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.177185,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.010000,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.059800,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.029013,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.356400,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [7]:
##Train test split
X=np.asarray(sonar.select_dtypes(include=float))
Y=sonar.select_dtypes(include=object)
Y['object']=Y['object'].map({'R':1, 'M':0})
Y=np.asarray(Y)
X_train, X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.3, random_state=101)

C:\Users\NITESH\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [10]:
##Logistic regression
log_fit=LogisticRegression()
log_fit.fit(X_train, Y_train)

# Displaying metrics on test data
logreg.display_binary_metrics(log_fit, X_test, Y_test)

Model Metrics
Observations...............        63
Coefficients...............        61
DF Error...................         2
Mean Absolute Error........    0.3412
Avg Squared Error..........    0.1539
Accuracy...................    0.8254
Precision..................    0.8929
Recall (Sensitivity).......    0.7576
F1-Score...................    0.8197
MISC (Misclassification)...     17.5%
     class 0...............     10.0%
     class 1...............     24.2%


     Confusion
       Matrix     Class 0   Class 1
Class 0.....        27         3
Class 1.....         8        25

In [11]:
##Appending predicted class to original dataframe and displaying first 15 rows
sonar['Predicted_class']=log_fit.predict(X)
sonar['Predicted_class']=sonar['Predicted_class'].map({1:'R', 0:'M'})
sonar.head()

,R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,...,R53,R54,R55,R56,R57,R58,R59,R60,object,Predicted_class
0,0.029013,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.310900,0.2111,...,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R,R
1,0.045300,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.333700,0.2872,...,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R,M
2,0.029013,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.177185,0.6194,...,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R,M
3,0.010000,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.059800,0.1264,...,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R,M
4,0.029013,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.356400,0.4459,...,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R,M